baseURL = 'https://blog.vmmazz.tech/'
languageCode = 'en-us'
title = 'My personal blog'
theme = 'anubis2'

[pagination]
pagerSize = 5

[params.author]
name = "Victor Mota Mazzei"
email = "victor@vmmazz.tech"
[markup.goldmark.renderer]
unsafe = true # Enable unsafe mode to have a better experience

[markup.highlight]
anchorLineNos      = false
codeFences         = true # tested with true and false. Both work.
noClasses          = true # If you run with markup.highlight.noClasses=false in your site configuration, you need a style sheet.
style              = 'base16-snazzy'
tabWidth           = 4
[params]
description = "Welcome to my personal blog, in here i will talk about programming, security, homelab and other stuffs"
dateFormat = "2006-01-02"
paginationSinglePost = true


colorTheme = "auto"
colorThemeSwitcher = true

readMore = false
readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = true
locale = "en-us"
math = false # true: enable mathjax globally (default is false)
toc = true

social = [
    { id = "github", url = "https://github.com/victor-mazzei"},
    { id = "email", url = "victor@vmmazz.tech"},
]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 4

[languages]
[languages.en]
languageName = "English"

[languages.br]
languageName = "Brasil"


[[languages.br.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[languages.br.menu.main]]
identifier = "about"
name = "Sobre"
url = "/sobre/"
weight = 2

[[languages.br.menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3

[[languages.br.menu.main]]
identifier = "archive"
name = "Arquivos"
url = "/posts/"
weight = 4

[languages.br.params]
languageCode = "pt-br"



[taxonomies]
category = "categories"
tag = "tags"
author = "authors"


